name: caller_x
description: "A production ready full-featured WhatsApp clone"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # ফায়ারবেস কোর ও ডাটাবেস
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0

  # কলিং ও অডিও/ভিডিও
  agora_rtc_engine: ^6.3.0
  permission_handler: ^11.3.1
  flutter_callkit_incoming: ^2.0.4

  # ভয়েস রেকর্ড, মিডিয়া ও ইউআই
  image_picker: ^1.1.0
  record: ^5.1.0
  audioplayers: ^6.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
